### ISSUE TITLE
esun

### ISSUE THREAD

**Issue by Daenyth** [lipu-linku/pali-nimi#26]
#### sona pu

NOUN market, shop, fair, bazaar, business transaction

#### sona Linku pi toki Inli

market, shop, fair, bazaar, business transaction

#### sona Linku pi toki pona

esun la jan tu li pana e ijo li kama jo e ijo ante; esun li ken ma li ken tomo. ma anu tomo la jan li ken pana e mani li ken kama jo e ijo.

#### sona ku

trading⁵, trade⁵, shopping⁵, deal⁴, commerce⁴, purchase⁴, sales⁴, buy⁴, transaction⁴, market⁴, sale³, exchange³, sell³, retail³, business³, shop³, store², commercial², financial², enterprise², economy², franchise²

**Comment by lipamanka** [comment]
how popular/important do we think the usage of esun for "swap" is? I think we should just add it. I also think we should consider adding more verbs after a semicolon. 

`market, shop, fair, bazaar, business transaction; swap, buy, sell, trade`

how's this?

**Comment by janPensa** [comment]
For comparison, here's Sonja's old definition from a [pre-pu wiki](https://archive.is/QG9Fs). Take with a pinch of salt.

> **esun**
> [noun]
> 
> 1. fair
> a community event where people socialize and exchange goods or information; exhibition, fair, function, get-together, market, occasion, reception, reunion, social affair, social event, social gathering
> 
> 2. trading place
> a place where goods are offered for trade; bazaar, farmers' market, marketplace, shop, shopping mall, store, trading place

**Comment by Daenyth** [comment]
I was thinking

> exchange, swap, barter, trade, business transaction; market, shop, fair, bazaar, place of business

I specifically wanted to highlight the non-currency-involved aspects because I think that's a common "miss" for learners

**Comment by janPensa** [comment]
Some of my first thoughts

* while "esun" was clearly meant to primarily mean a physical location, both pre-pu and in pu, in current usage the core meaning has shifted to be much closer to "trade", "commerce" and  "transaction" and similar. (You can also see this in ku data, where "shop" and "store" are relatively low in ranking, and "market" is probably only so high because it has a non-physical meaning as well)
* In current usage, "esun" as a verb is most commonly used for "buy". However, I think we should also include translations like "sell", "trade", "exchange" to keep it broad. Perhaps even put one or two of the more general verbs (like "trade", "exchange") in front of "sell".

**Comment by Daenyth** [comment]
Do we want to include "buy"/"sell" specifically when we have "business transaction"? Do we want to have "business transaction"?

**Comment by lipamanka** [comment]
> Do we want to include "buy"/"sell" specifically when we have "business transaction"? Do we want to have "business transaction"?

I think having both buy and sell is important because if we don't include sell people will see esun as exclusively buy or trade. We don't really need business transaction and I'm fine with removing it. 

> In current usage, "esun" as a verb is most commonly used for "buy".

I can't corroborate this. I don't speak toki pona with every person who speaks toki pona, but out of all the people I've spoken it with IRL (of which there are many), I've seen it used for "sell" and "swap" or even "breath" just as commonly as I've seen it used for "buy." So this is kind of a gut feeling and I don't think we should go off of it. but that's not exactly relevant, I just think if we're gonna be making descriptive statements we should say "I see xyz" instead of "xyz is most common" because I don't think any one speaker can judge what is most common in cases like this, i.e. we have different experiences. If we want to make true descriptive statements that aren't from our own individual perspectives, we'll have to do a study, not just a poll on ma pona. 

I'd also like to ask: how many of the people who use esun this way don't use it in day to day conversations? I'm *sure* that most people who respond to polls on ma pona pi toki pona don't use these words as often as those of us on the committee do. I'm starting to rethink our approach to descriptivism and I'll collect my thoughts at some point.

**Comment by Daenyth** [comment]
> In current usage, "esun" as a verb is most commonly used for "buy".

I missed commenting on this before, but I would strongly reject this. I think if you see it more often it's because people buy things more often than they sell them

>  I just think if we're gonna be making descriptive statements we should say "I see xyz" instead of "xyz is most common" because I don't think any one speaker can judge what is most common in cases like this, i.e. we have different experiences. If we want to make true descriptive statements that aren't from our own individual perspectives, we'll have to do a study, not just a poll on ma pona.

This is very important

**Comment by janPensa** [comment]
> I just think if we're gonna be making descriptive statements we should say "I see xyz" instead of "xyz is most common"

Yes, true. Thanks for reminding me.

I guess I felt comfortable making that claim because that's the way I've seen "esun e" being used for "buy" in what feels like 95-99% of the time. And I've seen this pattern across various different Toki Pona communities, and over a long period of time. At least since... \**checks the date of a certain project*\* ...oh, wow, already way back in 2017 I formed the opinion that "people are using 'esun e' to mean 'buy' way too much, and I don't like this lexicalization".

However, I also have the feeling that most of my memories about this occurring involved learners rather than proficient speakers, so my impressions probably don't reflect proficient usage very well. Or it's what Deni said, that people talk more often about buying things than about selling things.

Hmm... ku data does suggest that there's a kernel of truth in my old impression, though. "Purchase" and "buy" were translated as esun by 67% and 65% of respondents respectively, and "sell" only by 57%. Not a huge difference, and not as much as I would have predicted yesterday, but it's not a very small difference either. Enough to be in a different frequency category.

By the way, "trade" was translated as esun by 88%, which is much higher than all of those, but I have a feeling that that's possibly more because of its meaning as a noun than its meaning as a verb.

> I think having both buy and sell is important because if we don't include sell people will see esun as exclusively buy or trade. 

I actually lowkey prefer not mentioning buy and sell at all, to nudge people towards the idea that esun is broader than just those actions. But yeah, it's probably better, or at least more descriptivistic, to mention them.

> We don't really need business transaction and I'm fine with removing it.

I agree.

**Comment by janPensa** [comment]
So I guess the current state is something like

> trade, barter, exchange, swap, buy, sell; market, shop, fair, bazaar, place of business

(I moved "trade" and "barter" forwards, because those have a stronger connection to the "place of business" type translations)

Would it be worth adding "commerce"? Or perhaps "negotiation"?

**Comment by lipamanka** [comment]
jan Deni and i will go out and see which usages of esun feel naturalistic in an IRL setting tomorrow maybe lol. until then, looks good!

**Comment by lipamanka** [comment]
ASSIDE

also, idk if you agree with this terminology still, but 

> At least since... *checks the date of a certain project* ...oh, wow, already way back in 2017 I formed the opinion that "people are using 'esun e' to mean 'buy' way too much, and I don't like this lexicalization".

this isn't a lexicalization. you can't lexicalize something thats already in the lexicon. I think this is very important because the reason why lexicalization is bad for toki pona is that it increases the size of the lexicon. using esun exclusively for "buy" is a completely different issue, specifically one where we narrow one of our vague concepts, thereby making it more "complex" (as in specific), which is NOT changing the size of the lexicon at all.

**Comment by lipamanka** [comment]
i don't think we need negotiation. i'm not sure if i'd use esun to describe arguing with a child about how many scoops of ice cream they get. or maybe i would. what do you think

**Comment by lipamanka** [comment]
`trade, barter, exchange, swap, buy, sell; market, shop, fair, bazaar, place of business`

via @janPensa 

i like this one

**Comment by janPensa** [comment]
<details>
<summary>ASIDE: a response to lipamanka's comment about lexicalization (unimportant for the discussion, but click here to read it anyway)</summary>

> I think this is very important because the reason why lexicalization is bad for toki pona is that it increases the size of the lexicon. using esun exclusively for "buy" is a completely different issue, specifically one where we narrow one of our vague concepts, thereby making it more "complex" (as in specific)

Hmm... I disagree with this part.

In my first years as a tokiponist, I was in an environment that did not really discourage lexicalizations at all. Coming from that background and comparing it to the current state of the Toki Pona community, I believe that increasing the size of the lexicon is only a minor issue. (You need to learn thousands of words to be an intermediate speaker in a natlang. Even if you'd increase Toki Pona's lexicon by hundreds of units, that's still super easy to learn compared to basically every language.) In my opinion, the main problem with lexicalization is that it limits what the language can do.

People used to think Toki Pona is limited, and that it's simply impossible to meaningfully talk about complicated topics like science or politics or math. (There's even an entire page titled "Limitations" in pu's introduction that talks about this.) Nowadays the community consensus is that some things are much harder to talk about than others, but you _can_ (probably) actually say anything in Toki Pona. I think the main change that made this shift possible is that people depend less on lexicalizations and more on context to make clear what you mean, allowing Toki Pona words to mean more different things in more different contexts.

If "tomo tawa" can only mean a vehicle, "telo nasa" can only mean an alcoholic beverage, "tenpo esun" can only mean a week, and many more of those, then all of those combinations can't be used to express other ideas anymore. This limits the usefulness that the words in those phrases can have in other contexts.

Limiting transitive "esun" to only mean "to buy" is bad for exactly the same reason as why you don't want "telo nasa" to only mean alcohol. It unnecessarily limits what the word can do, closing the door for other ways of using it. That's why I called it a lexicalization in my earlier comment.

But yes, you're right, it's not a lexicalization. For something to be a lexicalization, it has to be two or more words, or at least multiple morphemes. I got my terminology mixed up there.</details>

**Comment by gregdan3** [comment]
i asked to be assigned to this and did not contribute bc i have no time management skills but hey i like the definition lmao
