### ISSUE TITLE
pan

### ISSUE THREAD

**Issue by Daenyth** [lipu-linku/pali-nimi#30]
#### sona pu

NOUN cereal, grain; barley, corn, oat, rice, wheat; bread, pasta

#### sona Linku pi toki Inli

cereal, grain; barley, corn, oat, rice, wheat; bread, pasta

#### sona Linku pi toki pona

moku tan kasi.

#### sona ku

bread⁵, grain⁵, wheat⁴, rice³, corn², carbohydrate²

**Comment by Daenyth** [comment]
> cereal grain (eg barley, corn, oat, rice, wheat); bread, pasta, cake, cookie

**Comment by gtbot2007** [comment]
imo cake is kinda suwi, but otherwise this is fine

**Comment by Daenyth** [comment]
Maybe we should say "pastry" instead of cake+cookie?

> cereal grain (eg barley, corn, oat, rice, wheat); bread, pasta, pastry

**Comment by janPensa** [comment]
I think grain products would also benefit a lot from a similar treatment to the grains. So like

> ..... ; grain product (e.g. bread, pasta, cake, cookie)

The examples so far seem pretty US/Europe-centric, so might be worth removing one or two and adding other examples. Some things that come to mind are noodles, tortillas, couscous, bulgur... And maybe the more general term "baked goods" is useful.

<hr/>

I did a little reseach on what "grain" and "cereal grain" mean exactly, and I think "cereal grain" is too specific. We'll definitely want to include some crops that aren't technically cereal grains, but fulfill basically the same role in various cultures, like quinoa and other "pseudocereals". Perhaps also some legumes like chickpeas and lentils?

[This overview](https://en.wikipedia.org/wiki/Grain#Classification) on the Wikipedia article about grains seems very useful to take a look at before deciding where we want to draw the line.

**Comment by wasokeli** [comment]
staple food
starchy food

**Comment by wasokeli** [comment]
potato should be included, whether explicitly or implicitly; it's a staple food

**Comment by janPensa** [comment]
> staple food
> starchy food

This is way too broad for my liking. That would include all kinds of tubers and roots, like potatoes, yams, turnips, carrots, as well as squash and some local banana species. Most of those are contentious edge cases that aren't usually referred to as "pan" in common usage, and some would probably be rejected outright by a majority.

I mulled it over a little while in the kitchen over the past hour, and I thought that "**cereal grains and similar crops**" might be a useful way to phrase it. (Perhaps even without the word "cereal"?) That easily includes grain-like foods that aren't technically cereals, and leaves enough space for people to determine for themselves whether seeds or potatoes or other edge cases are similar enough to grains in their nasin.

**Comment by lipamanka** [comment]
I'm in favor of "grains and starchy crops" because while bananas and carrots might have a lot of starch, I think it's pretty easy to draw a line between "squarely in pan" and "edge case" between pasta and beans here based on starch content. 
![image](https://github.com/lipu-linku/pali-nimi/assets/111026347/3f7bca52-69cc-46b4-a16b-12423d25cc9d)

Would you use pan for potato gnocchi? what about zucchini bread? Some recipes for cake don't use any grain based starch ingredients and they're still pan. a lot of starchy food happens to be staple food, but not all of it, and I don't think that's particularly important for pan. I also think including examples from around the world is cool here and the worst that could happen is someone looking up traditional types of pan in nonwestern cultures. So here's my idea: 

`grains, e.g. barley, corn, oat, rice, wheat; grain based and starchy foods, e.g. bread, cake, noodles, masa, congee, injera`

it's a little long but I think everything here is worth it. I like congee because it shows that pan doesn't have to be solid like a loaf of bread, and I like masa and injera because they're great examples of fermentative practices. 

Having "cereal" to talk about grains themselves would be confusing, and we already have a lot of examples from around the world so we don't need another example so I'm in favor of just leaving it out

**Comment by janPensa** [comment]
> Would you use pan for potato gnocchi? what about zucchini bread? Some recipes for cake don't use any grain based starch ingredients and they're still pan.

That depends on who you ask. If a baked product doesn't contain any grains but uses starchy vegetables instead, it is kili to me.

In my nasin "pan" primarily means "grain", and breads and pastas and such are only "pan" in the sense that they are *made of* grain crops, and that in many cultures they are the most common way to consume (certain) grains. Basically the same as how meat is "soweli" (or "waso" or whatever), but not if you use vegan imitation meat. Then the moku becomes _sama_ soweli, instead of _being_ soweli. At least in my opinion.

But of course I'm aware that my nasin is a lot stricter than the average. I'm okay with having "starchy foods" to have a broad and inclusive definition, especially if we give examples that suggest more grain-like products rather than french fries and mashed pumpkin, for example.

> grain based

Nitpick: "grain-based" is clearer if it functions as one modifier.

> I like congee because it shows that pan doesn't have to be solid like a loaf of bread

I think "porridge" (or otherwise "gruel") is more useful.

Porridge can be used to refer to liquidy foods based on all kinds of starchy plants, including congee. (Apparently Wikipedia even has a separate article for "[List of porridges](https://en.wikipedia.org/wiki/List_of_porridges)", lol.) And your point of "pan doesn't have to be solid" will be understood by more people if we use a more widely understood example that refers to many foods across many cultures.

**Comment by lipamanka** [comment]
> If a baked product doesn't contain any grains but uses starchy vegetables instead, it is kili to me.

So for you pan is abut the ingredients, not the thing itself? I'm not sure people agree with you. I certainly don't. if it looks like pan and tastes like pan and has the properties of pan, it's pan, right? Also I think if I pointed to a loaf of zucchini bread and said "kili" people would get confused. 
> I think "porridge" (or otherwise "gruel") is more useful.

"noodles" is an example that includes china (noodles were brought to Europe through the silk road from china) so I'd be willing to change congee to porridge.

**Comment by gtbot2007** [comment]
Most of the time you might not even know if it has any grains

**Comment by janPensa** [comment]
This comment can be skipped.

It goes into some depth about what I consider "pan" to be, but it isn't really directly relevant to the definition we're writing. Except maybe that I called nuts a kili-pan edge case.

<hr/>

> So for you pan is abut the ingredients, not the thing itself? 

No, _food in general_ is about the ingredients to me, because Toki Pona has a lot more words for ingredients (kili, soko, kasi, soweli, waso, kala, namako...) than for food products (moku). And as I said, "pan" refers primarily to grains to me, so in most cases it refers to the ingredient or the substance of the food, not the food itself as a finished product. Bread is one way to eat grains, just like salad is one way to eat vegetables, a hot dog is one way to eat pigs (or whatever other animals are in there), and applesauce is one way to eat apples.

You can call applesauce "ko kili", but when you're eating applesauce you can also just say "mi moku e kili", because apple is the main substance your food consists of. Similarly, in my nasin bread is more accurately "moku pan" (grain-related food), but I also use "pan" for short because (most) bread is basically another form of wheat, and wheat is pan.

In case you're interested to see this nasin in action, I also used it in the story I wrote for this year's [utala musi](http://utala.pona.la/). The first scene of [the second chapter of my story](http://utala.pona.la/toki-en-lipu/lipu-suli/mi-en-waso-Kaka.html#jan-ensi-li-lon-ma-tomo) takes place at a simple bakery, so there's a lot of "moku pan" used there, switched around with just "pan" in places to streamline the prose.

> Also I think if I pointed to a loaf of zucchini bread and said "kili" people would get confused.

I'm not familiar with zucchini bread, so I googled some recipes. Most of them seem to use wheat flour. If I google specifically for "flourless zucchini bread", I mostly find recipes that call for oat flour, or where you put whole oats into the blender. I found one that used ground walnuts instead, though.

You can use ground nuts instead of ground grains to get a *somewhat* cake-like consistency without grains, but nuts are also a kili-pan edge case. If you bake something without any grains, nuts or seeds as the base, and only use starchy vegetables and fruits like zucchinis and bananas, chances are the consistency is going to be not very bread-like.

> Most of the time you might not even know if it has any grains

With food from cultures I'm familiar with, I generally know more or less what it's made of, or I can make a good educated guess about whether it uses grains as a primary ingredient. At least, I think so.

**Comment by Daenyth** [comment]
potato la
(summarizing stuff from discord)

polls on different dates have been inconsistent on whether potatoes are pan. I suggest we leave it out of the main def but make a note of it in the commentary

**Comment by wasokeli** [comment]
inconsistent ala
when people were asked "are potatoes pan", they said yes
when people were asked to describe potatoes as either kili or pan, they picked kili

**Comment by Daenyth** [comment]
For me I think an important aspect is whether you can make flour from it and use that flour for things like bread. So corn, potato, rice, etc are all pan to me because of that

**Comment by wasokeli** [comment]
rice isn't pan because you can make bread from it. most rice consumption isn't in bread form. rice is pan because it's a staple starch

**Comment by Daenyth** [comment]
Right, I agree completely. I just think it encompasses both of those things

something like "staple starch. crop used for bread making" might be good additions

(why did I think this word would be easy to complete quickly? lol)

**Comment by wasokeli** [comment]
my preference would be to have "staple food" and "starchy food" in there separately, but having them smushed together is better than nothing

**Comment by wasokeli** [comment]
i think this is one of the most complicated words – it'll take more research to make it appropriately inclusive of many cultures.

a lot of toki pona is taught in conversation, without looking at dictionaries. and i think it would be good if the Linku definition is short and clear enough for people to remember a casual definition that's more accurate than "bread, rice, things like that", which i hear a lot.

**Comment by lipamanka** [comment]
> rice isn't pan because you can make bread from it. 

back to zuccini bread: if I make zuccini bread without any flour, is that not pan? That's a genuine question. Can this *not* be considered pan? because if the make and break of if something is pan or not is that it is made from either a staple or a starch, then this can't be pan, because the primary ingredient (zucchini) isn't pan. jan Pensa would probably say "no, this isn't pan." But I want to know what everyone else has to say about it.

![image](https://github.com/lipu-linku/pali-nimi/assets/111026347/40190458-bf5a-44c9-86be-6cce4ec3ea5f)
source: https://makethebestofeverything.com/2015/04/flourless-zucchininut-bread/

**Comment by wasokeli** [comment]
i would call that pan because it looks like bread

**Comment by wasokeli** [comment]
i don't think a food *has* to be a staple or starchy to be pan, but i think those terms include a lot of important pan

**Comment by lipamanka** [comment]
okay I was gonna type out a whole thing here but I think it's extremely tangential for the time being so when I'm done typing it up I'll put it on my website and we can revisit pan and kili perhaps.

**Comment by wasokeli** [comment]
i was able to persuade a nutrition nerd friend (gluten intolerant, nonwhite, started a food business) to help ensure the pan definition is inclusive of other cultures 

they argued that the term "staple food" is unnecessary, that the foods i'm thinking of are staples *because* they're starchy

for a complete definition, they suggested:
> grains, starchy foods, baked goods

**Comment by wasokeli** [comment]
their reasoning:
> high starch grains or tubers are a staple in almost every human culture
> every culture that has access to plant foods has a starchy staple
> not all cultures have a grain-based starchy staple (cassava, potatoes, plantains, breadfruit)
> 
> baked goods can include flourless chocolate cakes and zero-carb konjac noodles

**Comment by wasokeli** [comment]
they also shared some examples of pan
> pan: rice, corn, wheat, bread, tortillas, crackers, noodles
> ko pan: oatmeal, congee, mochi, corn grits, gruel
> kili pan: potatoes, yams, plantains, breadfruit
> pan kili: zucchini bread, cauliflower rice
> pan suwi: cake, cookies, pastries

**Comment by wasokeli** [comment]
if we're including a list of examples, then they suggested
> grains, starchy foods, baked goods; e.g. rice, bread, noodles, tortillas

**Comment by lipamanka** [comment]
I much prefer masa over tortillas (tortillas are traditionally made out of masa anyway), and I would really like injera to be on there.

**Comment by wasokeli** [comment]
> grains, starchy foods, baked goods; e.g. rice, bread, noodles, masa, injera

**Comment by lipamanka** [comment]
I love this one!

**Comment by lipamanka** [comment]
OH WAIT ACTUALLY: can we add porridge as one of the examples? so we can demonstrate that pan doesn't have to be dry.

**Comment by lipamanka** [comment]
`grains, starchy foods, baked goods; e.g. rice, bread, noodles, porridge, masa, injera`

**Comment by gtbot2007** [comment]
I feel like there should be a example that is not completely grain (sandwich? pizza?)

**Comment by lipamanka** [comment]
that's a good idea, I think pizza is a good idea. 
`grains, starchy foods, baked goods; e.g. rice, bread, pizza, noodles, porridge, masa, injera`

not sure about sandwich personally but I think I would definitely use pan for pizza

**Comment by Daenyth** [comment]
I use pan for sandwich 100% of the time

edit: I think we don't need to include it because "bread" covers it pretty well

**Comment by lipamanka** [comment]
hmmm do we want sandwitch or pizza? 
👀 sandwitch
🎉 pizza

**Comment by wasokeli** [comment]
i don't think either is necessary personally
i haven't seen people list every single ingredient for any food
your noka is still a noka when it's wearing a shoe
your pan is still a pan when there's namako on it

**Comment by lipamanka** [comment]
I think the point is that the namako can be part of the pan, not a seperate thing

**Comment by janPensa** [comment]
I like "grains, starchy foods, baked goods" 👍

I think I want one more grain in the examples list, because 1 grain crop to 6 food products is a very one-sided ratio. I'd maybe remove the pizza and put ~~"oats"~~ "barley" instead. So:

> grains, starchy foods, baked goods; e.g. rice, barley, bread, noodles, porridge, masa, injera

That seems more balanced to me.

(Edit: I first suggested "oats" as the second example, but "barley" probably makes for a slightly broader definition, because "oats" is associated with "porridge" in several English-speaking countries.)

**Comment by lipamanka** [comment]
I'm fine with that. (and yes, barley is probably better, for me growing up, porridge = oatmeal)

**Comment by wasokeli** [comment]
if we're adding another grain, let's do sorghum instead of barley, that way we're also adding to the list of cultures represented
> grains, starchy foods, baked goods; e.g. rice, bread, noodles, masa, porridge, injera, sorghum

**Comment by lipamanka** [comment]
amazing idea, 🚀 🚀 

i think we punched the ball out of the parking lot with this one /demolishes idiomaticy

**Comment by lipamanka** [comment]
actually can we put the grains next to each other 

`grains, starchy foods, baked goods; e.g. rice, sorghum, bread, noodles, masa, porridge, injera`

**Comment by wasokeli** [comment]
i'd like to put the most common foods at the beginning, and clarify specific cases (wet, fermented, not a food yet) at the end. i think it's easiest to skim that way

**Comment by lipamanka** [comment]
when i visited mexico masa was more prevalent than noodles by far. i do agree it's easier to skim but in my opinion grouping the grains together instead of having one as the first and the other as the last just feels better and after looking at it for the first time (possibly looking up a few of the examples), it would be easier to skim every subsequent viewing.

**Comment by wasokeli** [comment]
for me the list is overwhelmingly long, so every time i look at it it provides the same difficulty

**Comment by lipamanka** [comment]
i guess it's just personal preference then? idk id like someone else to weigh in

**Comment by wasokeli** [comment]
when i read "rice, bread" i perceive rice as a dish and not a grain on a plant
so sorghum feels weird as the only not-currently-food item, between food items
yes let's get more opinions

**Comment by gtbot2007** [comment]
I still think it should include something with a non-pan ingredient (ie. something like pizza or sandwich)

**Comment by Daenyth** [comment]
We should absolutely not stress about the *order* of the words we use. Just pick something and move on

**Comment by lipamanka** [comment]
because you don't seem to care, why don't you pick?

**Comment by Daenyth** [comment]
I see nothing wrong with https://github.com/lipu-linku/pali-nimi/issues/30#issuecomment-1700285245

**Comment by jnpoJuwan** [comment]
note to translators: 'masa' is definitely a word that won't exist (not even in Spanish, it just means 'dough' and lacks the narrower meaning). I propose either removing it in translations or just translating it as 'flour'
