### ISSUE TITLE
kepeken

### ISSUE THREAD

**Issue by wasokeli** [lipu-linku/pali-nimi#39]
the current definition includes "to use", which teaches beginners to say "kepeken e". i'd like to avoid creating beginner mistakes by revising that to "using"

sona Linku:
> to use, with, by means of

proposed replacement:
> (preposition) using, with, by means of

**Comment by ghost** [comment]
I feel that the word can function both as a verb and preposition, in which it takes "e" when it is a verb but not when it is a preposition (following the toki pona syntax). However, I may have learned incorrectly, and if "kepeken e" is actually not valid then I will, of course, stop using it in an incorrect way. pu gives that it is a preposition, while ku gives English translations (some of which are verbs or phrased as verbs) but not specifying what part of speech the word is. The current Linku data say this:
> Whether "kepeken" should be used with or without "e" in a predicative position (meaning "to use") remains controversial.
For reference, here are the definitions/translations given in pu and ku.
pu:
> PREPOSITION to use, with, by means of
ku:
> use⁵, utilize⁴, via³, employ³, used², operate², interact², equip²

If it turns out that I've been using this word wrong then oh well, if "kepeken e" is okay then oh well. Only jan Sonja can truly answer this matter.
